### ISSUE TITLE
update Multipoint with Point

### ISSUE THREAD

**Issue by shreeramneupane** [rgeo/activerecord-postgis-adapter#197] opened 2015-10-13 10:05 UTC
I have schema as like:

```
  enable_extension "plpgsql"
  enable_extension "postgis"

  create_table "locations", force: :cascade do |t|
    t.string   "name"
    t.geometry "positions",  limit: {:srid=>0, :type=>"multi_point"}
    t.datetime "created_at",                                          null: false
    t.datetime "updated_at",                                          null: false
  end
```

From rails console, I have create a recode as:
`loc = Location.create(name: 'Kathmandu road', positions: 'MULTIPOINT(27.7 85.33, 28.3 86.5)')`

Now I want to add another point say `POINT(29.1 87.1)` to `positions` field. So that `loc.positions` would give output `#<RGeo::Cartesian::MultiPointImpl:0x2e6a238 "MULTIPOINT ((27.7 85.33), (28.3 86.5), (29.1 87.1))">`.

Thus, How can i add `POINT` to `MULTIPOINT`?

**Comment by teeparham** [comment] 2018-11-09 16:42
Closing. This is not a bug. Please ask this question on StackOverflow.

**Closed by teeparham** 2018-11-09 16:42 UTC
