### ISSUE TITLE
"PG::UndefinedFile: ERROR:  could not open extension control file" when creating DB

### ISSUE THREAD

**Issue by Croge32** [rgeo/activerecord-postgis-adapter#288] opened 2018-07-10 18:20 UTC
So I've set up the database according to the README regarding installation of the gem and adjusting the database.yml file. I also installed postgis via Homebrew as well as downloaded the Postgres.app.

I'm getting this issue when I either run `rails db:create` or `rails db:gis:setup`:

```
PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory
: CREATE EXTENSION IF NOT EXISTS postgis
Couldn't create database for {"adapter"=>"postgis", "database"=>"db_name", "encoding"=>"utf8", "username"=>"postgres", "password"=>nil, "host"=>"db", "min_messages"=>"warning", "pool"=>5, "reaping_frequency"=>10, "timeout"=>5000}
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedFile: ERROR:  could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory
```

My database.yml:

```
development: &default
  adapter: postgis
  database: db_name
  encoding: utf8
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password:
  host: <%= ENV.fetch("DB_HOST") %>
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: db_name

production: &deploy
  <<: *default
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>

staging: *deploy
```

Any idea where the issue is in my setup? Seems like maybe I don't have PostGis installed properly? This app/database lives on a docker container as well, if that's relevant or requires some special setup.

**Comment by lym** [comment] 2018-07-30 16:42
@Croge32 What is the underlying Operating System in your container?

**Comment by teeparham** [comment] 2018-11-09 16:41
You're probably missing the PostGIS scripts. On Ubuntu, they're in a separate package (see comment from @lym). Try doing `psql -c "create extension postgis"`.

Closing, as this is not a bug with this adapter.

**Closed by teeparham** 2018-11-09 16:41 UTC

**Comment by raeesaroj** [comment] 2019-02-16 03:00
@geobudex Thanks, it works.

**Comment by shanbhardwaj** [comment] 2019-08-05 21:08
For future reference 
1. if you have upgraded from postgres10 to 11 then you will have reinstall the postgis extension again. 
2. if that also does not work then you will have to purge postgres 10 completely from the system and then install postgis.

**Comment by rcolomina** [comment] 2020-01-09 22:16
I can confirm that the following worked for me as well. This is indeed a problem on postgres10 kicking around along postgres11.
$ sudo apt install postgresql-10-postgis-scripts

**Comment by neldomarcelino** [comment] 2020-03-29 06:48
sudo apt-get install postgresql-10-postgis-scripts

**Comment by faisalrazap** [comment] 2021-05-01 05:19
For MacOS, installing postgis worked for me using below command:
```
brew install postgis
```

For Ubuntu, below command works:
```
sudo apt install postgresql-10-postgis-scripts
```

**Comment by Venus713** [comment] 2021-07-11 18:31
Hi @faisalrazap 
It does work for me. It's very helpful for me.
Thank you.

**Comment by rajkumardotnet90** [comment] 2023-07-24 16:23
Hi [faisalrazap](https://github.com/faisalrazap)

i have tried brew install postgis in my mac and it took almost 1 hr to complete but it did not worked for me.

Thanks
Rajkumar.C
