### ISSUE TITLE
Non-nil geometry value shows as nil when queried through rails

### ISSUE THREAD

**Issue by ashaw** [rgeo/activerecord-postgis-adapter#85] opened 2013-10-19 18:24 UTC
PostGIS ActiveRecord Adapter is returning nil for certain rows in my geometry column even though there are geometries in them that look fine in PG itself and QGIS.

For example: 

```
c = Thing.find_by_sql("select the_geom from things where area_id = '123abc'")
=> [#<Thing id: nil, the_geom: nil>]
```

Where, querying PG itself gives me

```
echo "select the_geom from things where area_id = '123abc'" | psql -t -U username -h localhost dbname
0106000020110F0000010000000103000000060000003A0700000157[...]
```

Oddly, it works with some rows:

```
c = Thing.find_by_sql("select the_geom from things where area_id = '456cde'")
=> [#<Thing id: nil, the_geom: #<RGeo::Cartesian::MultiPolygonImpl:0x3fda3811ef20 "MULTIPOLYGON (((-8279803.806488454 4963433.242760025, -8279612.788471473 4963068.609668385, -8279590.152201976 4963025.433246776 [...]
```

This is Rails 4 with activerecord-postgis-adapter 0.6.5 and rgeo-activerecord 0.5.0. The spatial column looks like

```
t.spatial "the_geom",       limit: {:srid=>3857, :type=>"geometry"}
```

**Comment by rogozind** [comment] 2015-06-06 19:50
We are having the same issue. We have acquired commercial data from Maponics. Out of 36000 records about 4700 have this issue. st_isvalid() is true but Rails cannot load geometry and return nil.  

Any way to debug?

**Comment by DanielHeath** [comment] 2015-06-07 07:06
I've found running a 'simplify' over the shape will often fix it, but haven't dug deep to find out why.

**Comment by rogozind** [comment] 2015-06-07 15:50
Thanks for the tip! It kind of worked but not each time. So I had to write a script to start small and increase tolerance by 10% till I get something which can be loaded. Often it takes up to 6-8 iterations to get to a loadable geometry.
They really should fix that bug...

**Comment by divinwind** [comment] 2015-07-22 10:59
+1

**Comment by slavajacobson** [comment] 2016-10-12 14:59
+1

**Comment by myidisnotthis** [comment] 2017-08-05 09:02
+1

**Comment by prasvin** [comment] 2017-12-26 16:40
+1

**Comment by teeparham** [comment] 2018-03-19 22:22
The rgeo gem currently silently returns nil when it can't parse a geometry.

That behavior will be changed with https://github.com/rgeo/rgeo/pull/183 in rgeo 2.0. Please comment/contribute/open a new issue there.

I'm closing this issue since it is not a bug with this adapter.

**Closed by teeparham** 2018-03-19 22:22 UTC
